services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://movieapp-mongo-1:27017/movieapp
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3031:3031"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
